### ISSUE TITLE
Update for augeasproviders_core 4.0.0

### ISSUE THREAD

**Issue by CodePhase** [voxpupuli/puppet-augeasproviders_nagios#7]
This module is limited to augeasproviders_core <= 3.0.0 yet augeasproviders_core 4.0.0 is currently released. I have not checked the breaking changes of augeasproviders_core's newest releases and may be able to create a pull request updating the compatibility if desired.

**Comment by kenyon** [comment]
I think a pull request updating the version range and the name to `puppet/augeasproviders_core` would be welcom.

**Comment by zilchms** [comment]
fixed in #10
